//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using Openapi.Utils;
    using System;
    
    /// <summary>
    /// Identifies the cryptographic algorithm family used with the key.<br/>
    /// 
    /// <remarks>
    /// If kty is set to RSA needs to be RSA-OAEP.<br/>
    /// If kty is set to EC needs to be ECDH-ES.
    /// </remarks>
    /// </summary>
    public enum Alg
    {
        [JsonProperty("RSA-OAEP")]
        RsaOaep,
        [JsonProperty("ECDH-ES")]
        EcdhEs,
    }

    public static class AlgExtension
    {
        public static string Value(this Alg value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static Alg ToEnum(this string value)
        {
            foreach(var field in typeof(Alg).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is Alg)
                    {
                        return (Alg)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum Alg");
        }
    }

}