//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using Openapi.Utils;
    
    public class BrokerResponseErrorDetails
    {

        /// <summary>
        /// The error type.
        /// </summary>
        [JsonProperty("type")]
        public string? Type { get; set; } = null;

        /// <summary>
        /// The error title.
        /// </summary>
        [JsonProperty("title")]
        public string? Title { get; set; } = null;

        /// <summary>
        /// The error detail.
        /// </summary>
        [JsonProperty("detail")]
        public string? Detail { get; set; } = null;

        /// <summary>
        /// The error code.
        /// </summary>
        [JsonProperty("code")]
        public string? Code { get; set; } = null;
    }
}