//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using Openapi.Utils;
    
    /// <summary>
    /// Specifies the different urls to callback to.
    /// </summary>
    public class CallbackUrls
    {

        /// <summary>
        /// Specifies the URL to redirect in case of success.<br/>
        /// 
        /// <remarks>
        /// If it is not a sandbox request needs to be https.
        /// </remarks>
        /// </summary>
        [JsonProperty("success")]
        public string Success { get; set; } = default!;

        /// <summary>
        /// Specifies the URL to redirect in case of abortion.<br/>
        /// 
        /// <remarks>
        /// If it is not a sandbox request needs to be https.
        /// </remarks>
        /// </summary>
        [JsonProperty("abort")]
        public string Abort { get; set; } = default!;

        /// <summary>
        /// Specifies the URL to redirect in case of error.<br/>
        /// 
        /// <remarks>
        /// If it is not a sandbox request needs to be https.
        /// </remarks>
        /// </summary>
        [JsonProperty("error")]
        public string Error { get; set; } = default!;
    }
}