//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using Openapi.Utils;
    using System;
    
    /// <summary>
    /// Key type of the JWK, specifying the cryptographic algorithm family used with the key.
    /// </summary>
    public enum Kty
    {
        [JsonProperty("rsa")]
        Rsa,
        [JsonProperty("ec")]
        Ec,
    }

    public static class KtyExtension
    {
        public static string Value(this Kty value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static Kty ToEnum(this string value)
        {
            foreach(var field in typeof(Kty).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is Kty)
                    {
                        return (Kty)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum Kty");
        }
    }

}