//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using Openapi.Utils;
    
    /// <summary>
    /// Message Transport Properties.
    /// </summary>
    public class MessageTransportProperties
    {

        /// <summary>
        /// Gets or sets the Message Level Encryption.
        /// </summary>
        [JsonProperty("messageLevelEncryption")]
        public string? MessageLevelEncryption { get; set; } = null;

        /// <summary>
        /// Gets or sets a value indicating whether gets or sets a value indicating if Hsm Signing is required.
        /// </summary>
        [JsonProperty("requireHsmSigning")]
        public bool? RequireHsmSigning { get; set; }
    }
}