//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using Openapi.Utils;
    using System;
    
    /// <summary>
    /// The selected flow used for this specific authentication session.<br/>
    /// 
    /// <remarks>
    /// To learn more about using the ```headless``` flow with Swedish BankID, please refer to &lt;a href=&quot;/identity-methods/sbid/setup/api-setup-sbid.html#headless-flow&quot;&gt;this example&lt;/a&gt;.
    /// </remarks>
    /// </summary>
    public enum SessionDataDtoFlow
    {
        [JsonProperty("headless")]
        Headless,
        [JsonProperty("redirect")]
        Redirect,
        [JsonProperty("embedded")]
        Embedded,
    }

    public static class SessionDataDtoFlowExtension
    {
        public static string Value(this SessionDataDtoFlow value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static SessionDataDtoFlow ToEnum(this string value)
        {
            foreach(var field in typeof(SessionDataDtoFlow).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is SessionDataDtoFlow)
                    {
                        return (SessionDataDtoFlow)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum SessionDataDtoFlow");
        }
    }

}