//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using Openapi.Models.Components;
    using Openapi.Utils;
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// Session information to be used within auth-api.
    /// </summary>
    public class SessionData
    {

        /// <summary>
        /// Session identifier (Globally unique).
        /// </summary>
        [JsonProperty("id")]
        public string? Id { get; set; } = null;

        /// <summary>
        /// The specified account ID used for the session.
        /// </summary>
        [JsonProperty("accountId")]
        public string AccountId { get; set; } = default!;

        /// <summary>
        /// The URL which you should direct your end-user to for performing the authentication.
        /// </summary>
        [JsonProperty("authenticationUrl")]
        public string? AuthenticationUrl { get; set; } = null;

        /// <summary>
        /// The URL that allows to check the authentication status.
        /// </summary>
        [JsonProperty("statusUrl")]
        public string? StatusUrl { get; set; } = null;

        /// <summary>
        /// The current status of the session.
        /// </summary>
        [JsonProperty("status")]
        public SessionDataStatus? Status { get; set; } = null;

        /// <summary>
        /// The status detail if the response is an error.
        /// </summary>
        [JsonProperty("statusDetail")]
        public string? StatusDetail { get; set; } = null;

        /// <summary>
        /// The IdP which was used by the end-user to authenticate.
        /// </summary>
        [JsonProperty("provider")]
        public string? Provider { get; set; } = null;

        /// <summary>
        /// The session&apos;s subject.
        /// </summary>
        [JsonProperty("subject")]
        public Subject? Subject { get; set; }

        /// <summary>
        /// Specifies the different urls to callback to.
        /// </summary>
        [JsonProperty("callbackUrls")]
        public CallbackUrls? CallbackUrls { get; set; }

        /// <summary>
        /// Gets or sets the session nonce.
        /// </summary>
        [JsonProperty("sessionNonce")]
        public string? SessionNonce { get; set; } = null;

        /// <summary>
        /// The idp data.
        /// </summary>
        [JsonProperty("idpData")]
        public Dictionary<string, string>? IdpData { get; set; } = null;

        [JsonProperty("environment")]
        public SessionEnvironment? Environment { get; set; }

        [JsonProperty("error")]
        public BrokerResponseErrorDetails? Error { get; set; }

        /// <summary>
        /// Message Transport Properties.
        /// </summary>
        [JsonProperty("messageTransportProperties")]
        public MessageTransportProperties? MessageTransportProperties { get; set; }

        /// <summary>
        /// A set of support optional tags to group and filter webhooks.
        /// </summary>
        [JsonProperty("tags")]
        public List<string>? Tags { get; set; } = null;

        /// <summary>
        /// Gets or sets the transaction id.
        /// </summary>
        [JsonProperty("transactionId")]
        public string? TransactionId { get; set; } = null;

        /// <summary>
        /// A list of Identity Providers (IdPs) that can be used for authentication.<br/>
        /// 
        /// <remarks>
        /// If not specified, the end-user will be able to choose from all IdPs associated with your Signicat account.<br/>
        /// The maximum length for each Provider is 30.
        /// </remarks>
        /// </summary>
        [JsonProperty("allowedProviders")]
        public List<string>? AllowedProviders { get; set; } = null;

        /// <summary>
        /// The desired language for the UI. Expected format ISO 639-1.<br/>
        /// 
        /// <remarks>
        /// If the requested language is not available, it will automatically default to English (en).<br/>
        /// Some IdPs may have a different fallback language due to regional considerations.
        /// </remarks>
        /// </summary>
        [JsonProperty("language")]
        public string? Language { get; set; } = null;

        /// <summary>
        /// The selected flow used for this specific authentication session.<br/>
        /// 
        /// <remarks>
        /// To learn more about using the ```headless``` flow with Swedish BankID, please refer to &lt;a href=&quot;/identity-methods/sbid/setup/api-setup-sbid.html#headless-flow&quot;&gt;this example&lt;/a&gt;.
        /// </remarks>
        /// </summary>
        [JsonProperty("flow")]
        public SessionDataFlow Flow { get; set; } = default!;

        /// <summary>
        /// The themeId you want to use for this specific authentication session.<br/>
        /// 
        /// <remarks>
        /// If not specified, the default theme for your account will be used.
        /// </remarks>
        /// </summary>
        [JsonProperty("themeId")]
        public string? ThemeId { get; set; } = null;

        /// <summary>
        /// The attributes you wish to get back from the authentication of the end-user.<br/>
        /// 
        /// <remarks>
        /// To find a list of which attributes can be requested, please see documentation for that specific ID method which<br/>
        /// can be found on &lt;a href=&quot;https://developer.signicat.com/identity-methods/&quot;&gt;https://developer.signicat.com/identity-methods/&lt;/a&gt;.<br/>
        /// <br/>
        /// Defaults to empty.
        /// </remarks>
        /// </summary>
        [JsonProperty("requestedAttributes")]
        public List<string> RequestedAttributes { get; set; } = default!;

        /// <summary>
        /// An external reference for you, will be returned as a URL parameter on callbackUrls.
        /// </summary>
        [JsonProperty("externalReference")]
        public string? ExternalReference { get; set; } = null;

        /// <summary>
        /// An usage external reference for you to group your billing.
        /// </summary>
        [JsonProperty("usageReference")]
        public string? UsageReference { get; set; } = null;

        /// <summary>
        /// Lifetime of session in seconds (Default is 1200 seconds). It has a soft-minimum value of 300 seconds, which means if the value set is<br/>
        /// 
        /// <remarks>
        /// less then 300, it will be automatically set to 300 seconds.
        /// </remarks>
        /// </summary>
        [JsonProperty("sessionLifetime")]
        public int? SessionLifetime { get; set; } = null;

        /// <summary>
        /// This specifies the domain you want to use for this specific session.<br/>
        /// 
        /// <remarks>
        /// The domain will be visible in the end-user&apos;s browser.<br/>
        /// This domain needs to be correctly configured on your account!
        /// </remarks>
        /// </summary>
        [JsonProperty("requestDomain")]
        public string? RequestDomain { get; set; } = null;

        /// <summary>
        /// DateTime calculated field expiry of session.
        /// </summary>
        [JsonProperty("expiresAt")]
        public DateTime? ExpiresAt { get; set; } = null;
    }
}