//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using Openapi.Utils;
    
    public class SessionEnvironment
    {

        /// <summary>
        /// The IpAddress of the end user.
        /// </summary>
        [JsonProperty("ipAddress")]
        public string? IpAddress { get; set; } = null;

        /// <summary>
        /// The request user agent.
        /// </summary>
        [JsonProperty("userAgent")]
        public string? UserAgent { get; set; } = null;
    }
}