//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using Openapi.Models.Components;
    using Openapi.Utils;
    using System.Collections.Generic;
    
    /// <summary>
    /// The Session to be created.
    /// </summary>
    public class SessionRequestDto
    {

        /// <summary>
        /// The session&apos;s prefilled input information (it is required at least one value).
        /// </summary>
        [JsonProperty("prefilledInput")]
        public PrefilledInput? PrefilledInput { get; set; }

        /// <summary>
        /// Additional parameters that modify the authentication flow. Depends on selected IdP.<br/>
        /// 
        /// <remarks>
        /// See &lt;a href=&quot;https://developer.signicat.com/identity-methods/&quot;&gt;developer documentation&lt;/a&gt; for details.
        /// </remarks>
        /// </summary>
        [JsonProperty("additionalParameters")]
        public Dictionary<string, string>? AdditionalParameters { get; set; } = null;

        /// <summary>
        /// Specifies the different urls to callback to.
        /// </summary>
        [JsonProperty("callbackUrls")]
        public CallbackUrls? CallbackUrls { get; set; }

        /// <summary>
        /// Encryption key information.
        /// </summary>
        [JsonProperty("encryptionPublicKey")]
        public EncryptionKey? EncryptionPublicKey { get; set; }

        /// <summary>
        /// Specifies the LoA (Level of Assurance).
        /// </summary>
        [JsonProperty("requestedLoa")]
        public RequestedLoa? RequestedLoa { get; set; } = null;

        /// <summary>
        /// A set of support optional tags to group and filter webhooks.<br/>
        /// 
        /// <remarks>
        /// The maximum length for each tag is 100.
        /// </remarks>
        /// </summary>
        [JsonProperty("tags")]
        public List<string>? Tags { get; set; } = null;

        /// <summary>
        /// If specified the embedded view will return to this URL after authentication is completed (successfully or not). If not specified, a success or error screen will be shown inside the embedded view.
        /// </summary>
        [JsonProperty("returnUrl")]
        public string? ReturnUrl { get; set; } = null;

        /// <summary>
        /// Specify the parent domains that will embed the authentication. This will be used for content security frame ancestor header if set, as an extra security mechanism to protect against clickjacking.
        /// </summary>
        [JsonProperty("embeddedParentDomains")]
        public List<string>? EmbeddedParentDomains { get; set; } = null;

        /// <summary>
        /// A list of Identity Providers (IdPs) that can be used for authentication.<br/>
        /// 
        /// <remarks>
        /// If not specified, the end-user will be able to choose from all IdPs associated with your Signicat account.<br/>
        /// The maximum length for each Provider is 30.
        /// </remarks>
        /// </summary>
        [JsonProperty("allowedProviders")]
        public List<string>? AllowedProviders { get; set; } = null;

        /// <summary>
        /// The desired language for the UI. Expected format ISO 639-1.<br/>
        /// 
        /// <remarks>
        /// If the requested language is not available, it will automatically default to English (en).<br/>
        /// Some IdPs may have a different fallback language due to regional considerations.
        /// </remarks>
        /// </summary>
        [JsonProperty("language")]
        public string? Language { get; set; } = null;

        /// <summary>
        /// The selected flow used for this specific authentication session.<br/>
        /// 
        /// <remarks>
        /// To learn more about using the ```headless``` flow with Swedish BankID, please refer to &lt;a href=&quot;/identity-methods/sbid/setup/api-setup-sbid.html#headless-flow&quot;&gt;this example&lt;/a&gt;.<br/>
        /// If flow is set to Redirect the field CallbackUrls is required.
        /// </remarks>
        /// </summary>
        [JsonProperty("flow")]
        public SessionRequestDtoFlow Flow { get; set; } = default!;

        /// <summary>
        /// The themeId you want to use for this specific authentication session.<br/>
        /// 
        /// <remarks>
        /// If not specified, the default theme for your account will be used.
        /// </remarks>
        /// </summary>
        [JsonProperty("themeId")]
        public string? ThemeId { get; set; } = null;

        /// <summary>
        /// The attributes you wish to get back from the authentication of the end-user.<br/>
        /// 
        /// <remarks>
        /// To find a list of which attributes can be requested, please see documentation for that specific ID method which<br/>
        /// can be found on &lt;a href=&quot;https://developer.signicat.com/identity-methods/&quot;&gt;https://developer.signicat.com/identity-methods/&lt;/a&gt;.<br/>
        /// <br/>
        /// Defaults to empty.
        /// </remarks>
        /// </summary>
        [JsonProperty("requestedAttributes")]
        public List<string> RequestedAttributes { get; set; } = default!;

        /// <summary>
        /// An external reference for you, will be returned as a URL parameter on callbackUrls.
        /// </summary>
        [JsonProperty("externalReference")]
        public string? ExternalReference { get; set; } = null;

        /// <summary>
        /// An usage external reference for you to group your billing.
        /// </summary>
        [JsonProperty("usageReference")]
        public string? UsageReference { get; set; } = null;

        /// <summary>
        /// Lifetime of session in seconds (Default is 1200 seconds). It has a soft-minimum value of 300 seconds, which means if the value set is<br/>
        /// 
        /// <remarks>
        /// less then 300, it will be automatically set to 300 seconds.
        /// </remarks>
        /// </summary>
        [JsonProperty("sessionLifetime")]
        public int? SessionLifetime { get; set; } = null;

        /// <summary>
        /// This specifies the domain you want to use for this specific session.<br/>
        /// 
        /// <remarks>
        /// The domain will be visible in the end-user&apos;s browser.<br/>
        /// This domain needs to be correctly configured on your account!
        /// </remarks>
        /// </summary>
        [JsonProperty("requestDomain")]
        public string? RequestDomain { get; set; } = null;
    }
}