//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using Openapi.Models.Components;
    using Openapi.Utils;
    
    /// <summary>
    /// The session&apos;s subject.
    /// </summary>
    public class Subject
    {

        /// <summary>
        /// The identifier of the subject.
        /// </summary>
        [JsonProperty("id")]
        public string? Id { get; set; } = null;

        /// <summary>
        /// The idp identifier of the subject.
        /// </summary>
        [JsonProperty("idpId")]
        public string? IdpId { get; set; } = null;

        /// <summary>
        /// The full name of the subject.
        /// </summary>
        [JsonProperty("name")]
        public string? Name { get; set; } = null;

        /// <summary>
        /// The first name of the subject.
        /// </summary>
        [JsonProperty("firstName")]
        public string? FirstName { get; set; } = null;

        /// <summary>
        /// The middle name of the subject.
        /// </summary>
        [JsonProperty("middleName")]
        public string? MiddleName { get; set; } = null;

        /// <summary>
        /// The last name of the subject.
        /// </summary>
        [JsonProperty("lastName")]
        public string? LastName { get; set; } = null;

        /// <summary>
        /// The date of birth of the subject.
        /// </summary>
        [JsonProperty("dateOfBirth")]
        public string? DateOfBirth { get; set; } = null;

        /// <summary>
        /// The subject&apos;s National Identity Number information.
        /// </summary>
        [JsonProperty("nin")]
        public Nin? Nin { get; set; }

        /// <summary>
        /// The Email of the subject.
        /// </summary>
        [JsonProperty("email")]
        public string? Email { get; set; } = null;

        /// <summary>
        /// Example idp attribute
        /// </summary>
        [JsonProperty("attribute_1")]
        public object? Attribute1 { get; set; }

        /// <summary>
        /// Example idp attribute
        /// </summary>
        [JsonProperty("attribute_2")]
        public object? Attribute2 { get; set; }
    }
}